environment:
  nuget_api_key:
    secure: HKxej4Q7DMIemGxrAp+FvFRhuBiyP5DnnB6JToqF5W/sUTPNwQoi9op12umSFviH

image: Ubuntu

before_build:
- chmod +x ./build.sh

build_script:
- ./build.sh --target complete-workflow --nuget-key $env:nuget_api_key
