environment:
  NUGET_KEY:
    secure: HKxej4Q7DMIemGxrAp+FvFRhuBiyP5DnnB6JToqF5W/sUTPNwQoi9op12umSFviH

image: Ubuntu

before_build:
- chmod +x ./build.sh

build_script:
- ./build.sh --target complete-workflow --nuget-key "$env:NUGET_KEY"
