environment:
  NUGET_KEY:
    secure: HKxej4Q7DMIemGxrAp+FvFRhuBiyP5DnnB6JToqF5W/sUTPNwQoi9op12umSFviH

image: Ubuntu

build_script:
- ps: >-
    ./build.ps1 --target complete-workflow --nuget-key $env:NUGET_KEY
