version: 1.0.{build}

environment:
  NUGET_KEY:
    secure: yTJOXDOWg52hjjJFxtJNqq0uRfi8pHiC2ilKFXsJoDT6XjM13bRgvSyYaf4z9wJe

image: Ubuntu

test_script:
- sudo ./build.sh --target test

build_script:
- sudo ./build.sh --target compile --configuration release

deploy_script:
- sudo ./build.sh --target publish --nuget-key $env:NUGET_KEY
