version: 1.0.{build}

configuration: Release

image: Ubuntu

test_script:
- dotnet test ./src/

build_script:
- dotnet build ./src/ -v m -c Release

after_build:
  - dotnet pack Composite --no-build

artifacts:
- path: '**\*.nupkg'
  name: NuGet

deploy:
- provider: NuGet
  server: NuGet.org
  api_key:
    secure: yTJOXDOWg52hjjJFxtJNqq0uRfi8pHiC2ilKFXsJoDT6XjM13bRgvSyYaf4z9wJe
  on:
    branch: master
    appveyor_repo_tag: true
