version: 1.0.{build}

configuration: Release

image: Ubuntu

test_script:
- dotnet test ./src/

build_script:
- dotnet build ./src/ -v m -c Release

build:
  publish_nuget: true

deploy:
  provider: NuGet
  api_key:
    secure: EBAvPnMs/+UOBs8EEz0DGyOvFXDxkEACjlwcOTvEorxy0we5SHLwfELS+cox2aFw
  skip_symbols: false
  artifact: /.*\.nupkg/
