environment:
  NUGET_KEY:
    secure: yTJOXDOWg52hjjJFxtJNqq0uRfi8pHiC2ilKFXsJoDT6XjM13bRgvSyYaf4z9wJe

image: Ubuntu

before_build:
- chmod +x ./build.sh

build_script:
- ./build.sh --target complete-workflow --nuget-key $env:NUGET_KEY
